
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging:
#  file: C:/Users/welcom/Desktop/logs/microservice.log

appender:
  file:
    type: File
    name: LOGFILE
    fileName: C:/Users/welcom/Desktop/logs/microservice.log
    filter:
      threshold:
        type: ThresholdFilter
        level: info