server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
  jackson:
    serialization:
      INDENT_OUTPUT: true

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sanaullahkhan9943/lcwd-microservices
          clone-on-start: true
