server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost:8085

                  #eureka:
                  #  instance:
                  #    prefer-ip-address: true
                  #  client:
                  #    fetch-registry: true
                  #    register-with-eureka: true
                  #    service-url:
                  #      defaultZone: http://localhost:8761/eureka

#logging:
#  file: C:/Users/welcom/Desktop/logs/microservice.log

appender:
  file:
    type: File
    name: LOGFILE
    fileName: C:/Users/welcom/Desktop/logs/microservice.log
    layout:
      type: PatternLayout
      pattern: [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n
    filter:
      threshold:
        type: ThresholdFilter
        level: info


